version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: house-hunting-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: house-hunting-system
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./server/src/utils/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - house-hunting-network

  # Redis for session management and caching
  redis:
    image: redis:7.2-alpine
    container_name: house-hunting-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - house-hunting-network

  # Backend API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: house-hunting-server
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/house-hunting-system?authSource=admin
      REDIS_URL: redis://redis:6379
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - house-hunting-network

  # Frontend React App
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: house-hunting-client
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      REACT_APP_STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - house-hunting-network

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: house-hunting-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - client
      - server
    networks:
      - house-hunting-network
    profiles:
      - production

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  house-hunting-network:
    driver: bridge